services:
  mqtt:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped

  nvr:
    container_name: nvr
    depends_on:
      - mqtt
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "1024mb" # https://docs.frigate.video/installation#calculating-required-shm-size
    devices:
      # - /dev/bus/usb:/dev/bus/usb # pass USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # pass PCIe Coral TPU, follow driver instructions here https://coral.ai/d>
      # - /dev/dri/renderD128 # pass GPU for hardware stream decode
    volumes:
      - ./volumes/frigate/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nas-nvr-recordings:/media/frigate
      # Optional: 2GB of memory, reduces SSD/SD Card wear
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    environment:
      - "FRIGATE_CLIENT_LAN_IP=${CLIENT_IP}"
      - "FRIGATE_RTSP_PASSWORD=${RTSP_PASSWORD}"
      # AMD APU ffmpeg hw acceleration
      # - "FRIGATE_LIBVA_DRIVER_NAME=radeonsi"
      # - "LIBVA_DRIVER_NAME=radeonsi"
    ports:
      - ${CLIENT_IP}:5000:5000/tcp
      # Restream
      - ${CLIENT_IP}:8554:8554
      # Use WebRTC for better live view
      # https://docs.frigate.video/configuration/live/#webrtc-extra-configuration
      - ${CLIENT_IP}:8555:8555

  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nvr-nginx
    depends_on:
      - nvr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./volumes/nginx/config:/config
    ports:
      - ${CLIENT_IP}:443:443
    restart: unless-stopped
