version: "3"

services:
  mqtt:
    image: eclipse-mosquitto:1.6
    restart: unless-stopped
  nvr:
    container_name: nvr
    depends_on:
      - mqtt
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # https://docs.frigate.video/installation#calculating-required-shm-size
    # devices:
    # - /dev/bus/usb:/dev/bus/usb # passes the USB Coral, needs to be modified for other versions
    # - /dev/apex_0:/dev/apex_0 # passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
    # GPU acceleration
    # - /dev/dri/renderD128
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./volumes/config.yml:/config/config.yml:ro"
      - "./volumes/storage:/media/frigate"
      # - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
      #   target: /tmp/cache
      #   tmpfs:
      #     size: 1000000000
    environment:
      # - "FRIGATE_CAMERA_LAN_IP=${FRIGATE_CAMERA_LAN_IP}"
      # - "FRIGATE_CAMERA_LAN_RTSP_PORT=${FRIGATE_CAMERA_LAN_RTSP_PORT}"
      - "FRIGATE_CLIENT_LAN_IP=${FRIGATE_CLIENT_LAN_IP}"
      - "FRIGATE_RTSP_PASSWORD=password"
      # AMD APU ffmpeg hw acceleration
      # - "FRIGATE_LIBVA_DRIVER_NAME=radeonsi"
      # - "LIBVA_DRIVER_NAME=radeonsi"
    ports:
      - ${FRIGATE_CLIENT_LAN_IP}:5000:5000/tcp
