birdseye:
  mode: continuous
  width: 1920
  height: 1080
  quality: 1

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:testing123@192.168.50.101:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
        - path: rtsp://admin:testing123@192.168.50.101:554/live
          roles:
            - record

detect:
  width: 1920
  height: 1080

# Use PCIe Coral Edge TPU for inference
detectors:
  coral1:
    type: edgetpu
    device: pci:0

go2rtc:
  streams:
    camera_1:
      - rtsp://admin:testing123@192.168.50.101:554/live
  webrtc:
    candidates:
      - 192.168.0.20:8555
      # STUN is only required if exposing through NAT
      # - stun:8555

live:
  height: 1080
  quality: 1

mqtt:
  enabled: False

objects:
  track:
    - person
    - car
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow

record:
  enabled: True
  sync_recordings: True
  retain:
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
  events:
    retain:
      default: 90
      mode: active_objects

rtmp:
  enabled: False # <-- RTMP should be disabled if your stream is not H264

snapshots:
  enabled: True
  clean_copy: True
  bounding_box: True
  crop: False
  retain:
    default: 90
    objects:
      person: 15
  quality: 100

telemetry:
  version_check: False

ui:
  live_mode: webrtc
  timezone: America/Los_Angeles
  time_format: 24hour
  strftime_fmt: "%Y-%m-%d %H:%M"
