cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:testing123@192.168.50.101:554/cam/realmonitor?channel=1&subtype=2
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/camera_1
          roles:
            - record
    ui:
      order: 1

database:
  path: /db/frigate.db

# Use PCIe Coral Edge TPU for inference
detectors:
  coral1:
    type: edgetpu
    device: pci:0

go2rtc:
  streams:
    camera_1:
      - rtsp://admin:testing123@192.168.50.101:554/live
  webrtc:
    candidates:
      - 192.168.0.20:8555
      # STUN is only required if exposing through NAT
      # - stun:8555

motion:
  threshold: 30

mqtt:
  enabled: true
  host: {FRIGATE_MQTT_HOST}
  port: 11883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

objects:
  track:
    - person
    - car
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow

record:
  enabled: true
  sync_recordings: true
  retain:
    # NOTE: This should be set to 0 and retention should be defined in events section below
    #       if you only want to retain recordings of events.
    days: 0
  events:
    retain:
      default: 90
      mode: active_objects

snapshots:
  enabled: true
  clean_copy: true
  bounding_box: true
  crop: false
  retain:
    default: 90
    objects:
      person: 45
  quality: 100

telemetry:
  version_check: false

ui:
  timezone: America/Los_Angeles
  time_format: 24hour
  strftime_fmt: '%Y-%m-%d %H:%M'

version: 0.14
