cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:testing123@192.168.50.101:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

detect:
  width: 1920
  height: 1080

# Use PCIe Coral Edge TPU for inference
detectors:
  coral1:
    type: edgetpu
    device: pci:0

go2rtc:
  streams:
    camera_1:
      - rtsp://admin:testing123@192.168.50.101:554/live
  webrtc:
    candidates:
      - 192.168.1.20:8555
      # STUN is only required if exposing through NAT
      # - stun:8555

live:
  height: 960 # 1920 / 2
  quality: 1

mqtt:
  enabled: False

record:
  enabled: True
  sync_recordings: True
  retain:
    days: 0
  events:
    retain:
      default: 90
      mode: active_objects

rtmp:
  enabled: False # <-- RTMP should be disabled if your stream is not H264

snapshots:
  enabled: True
  clean_copy: True
  bounding_box: True
  crop: False
  retain:
    default: 90
    objects:
      person: 15
  quality: 100

telemetry:
  version_check: False

ui:
  live_mode: webrtc
  timezone: America/Los_Angeles
