mqtt:
  enabled: False

cameras:
  camera_1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:testing123@192.168.50.101:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect

rtmp:
  enabled: False # <-- RTMP should be disabled if your stream is not H264

detect:
  width: 1920
  height: 1080

go2rtc:
  streams:
    camera_1:
      - rtsp://admin:testing123@192.168.50.101:554/live
  webrtc:
    candidates:
      - 192.168.1.20:8555
      # STUN is only required if exposing through NAT
      # - stun:8555

# Use PCIe Coral Edge TPU for inference
detectors:
  coral1:
    type: edgetpu
    device: pci:0
